### ISSUE TITLE
Executor in rclc crystal version

### ISSUE THREAD

**Issue by Sdehnavi** [micro-ROS/rclc#19]
Hi,
I am looking into the implementation of RCLC for the crystal version but it seems that the executor is not implemented in this version of microROS. Would you please explain why it has been removed? and how do you make the program run without executors?

**Comment by ralph-lange** [comment]
Hi @Sdehnavi, you're right, the rclc Executor was developed for Dashing only. We do not plan a backport to Crystal as it is already EOL. In the Crystal versions of our demos, we called rcl_wait explictitly with hand-written waitsets, see for example https://github.com/micro-ROS/apps/blob/crystal/examples/kobuki/thin_kobuki_node.cxx#L330.

**Comment by Sdehnavi** [comment]
@ralph-lange Thanks for your response. 
So it means that no scheduling happens between callbacks like timers and subscriptions?
Maybe I am confused a bit with the usage of executor and the relation between nodes, executors and processes!

**Comment by ralph-lange** [comment]
Without the rclc executor you have to implement the scheduling manually by deciding by means of the waitset which subscription, timer, ... to process next.
In contrast, the rclc executor implements its own scheduling scheme, but gives the user very fine-grained control about it. In particular, it allows

- defining the order in which the callbacks are executed in case of multiple parallel events,
- defining custom trigger conditions for such events, and
- distributing the callbacks of a node (or multiple nodes together) to multiple executor instances, which are again bound to multiple threads/processes of the underlying OS or RTOS.

See https://github.com/micro-ROS/rclc/blob/master/rclc/README.md for the full documentation.

Please note that the last feature, i.e. a fine-grained API to assign the callbacks or callback groups of one or more nodes to different executors, is currently not available in the standard rclcpp Executor. Yet, it has been under discussion for quite a while, cf. for example the [slides of my lightning talk at ROSCon 2018](https://roscon.ros.org/2018/presentations/ROSCon2018_Lightning1_4.pdf).

**Comment by Sdehnavi** [comment]
@ralph-lange Thanks a lot for the nice explanation.
