### ISSUE TITLE
Convenience functions for best effort

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/rclc#28]
Hello, I'm porting micro-ROS examples to RCLC and I found that it would be interesting to have a convenience function that handles RCL code like this one:

```
rcl_subscription_options_t led_subscription_ops = rcl_subscription_get_default_options();
led_subscription_ops.qos.reliability = RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT;
rcl_subscription_t led_subscription = rcl_get_zero_initialized_subscription();
rcl_subscription_init(&led_subscription, &node, ROSIDL_GET_MSG_TYPE_SUPPORT(std_msgs, msg, Bool), "/sensors/led", &led_subscription_ops)
```

Since we support a `RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT` in the micro-ROS RMW by using Micro XRCE-DDS best effort streams (and of course generating DDS best effort entities in the agent side) I think that it would be interesting to implement something that addresses these use cases.

I think that best effort subscribers and publishers are interesting in micro-ROS when high transmission rates and no reliability are required 

What do you think @JanStaschulat @ralph-lange @julibert?

**Comment by JanStaschulat** [comment]
Yes, also in the rclc-examples there are cases in which the qos-parameters need to be changed. @pablogs9 Currently, I am also using the rcl_subscription_init directly for changing rcl_subscription_options_t parameters. We could provide a convenience function just for this type RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT. 

Are there any other types that would be interesting?

**Comment by pablogs9** [comment]
In all our use cases the QoS is the default (reliable both in DDS and Micro XRCE-DDS) or this best effort. So I think that its ok to provide only this convenience.

**Comment by JanStaschulat** [comment]
see pull request https://github.com/micro-ROS/rclc/pull/34
