### ISSUE TITLE
ros_to_dds interface

### ISSUE THREAD

**Issue by pablogs9** [micro-ROS/rclc#29]
Hi everyone. I was wondering what should we do with this ros_to_dds interface exposed [here](https://docs.ros2.org/dashing/developer_overview.html#internal-api-architecture-overview):

![image](https://user-images.githubusercontent.com/7647884/83153323-1c4af300-a0ff-11ea-9dec-9a8a34f18e35.png)

We are using it in micro-ROS to configure the RMW at runtime, there are examples here: https://github.com/micro-ROS/micro-ROS-demos/blob/b3ecd0dc45b83847640071a9bb5b4ec18c33982f/rcl/configuration_example/configured_publisher/main.c#L37

As you can see, for us it is ok to have access to the `rmw_init_options_t` of the RCL. We provide some functions to configure these init options (for example for configuring the micro-ROS agent IP and port).

You think it is better:
* to expose these `rmw_init_options_t` on the RCLC API 
* or, letting the user doing something like:

```
...
rclc_support_t support;
rmw_init_options_t* rmw_options = rcl_init_options_get_rmw_init_options(&support.init_options);
...
```

I have doubts about mixing RCLC, RCL and RMW in the same code. What do you think?

**Comment by ralph-lange** [comment]
I always draw rclc on the same layer as rcl, to explain that it does not create a new layer on top of rcl (as rclcpp and rclpy do) but that it complements rcl with some convenience functions and structs to make the combination rcl+rclc a full C API for ROS 2 / micro-ROS. Therefore, I do not see any problem in adding rclc to the existing mix of rcl and rmw.

**Comment by pablogs9** [comment]
I agree, so I'll port the demos and examples with this idea in mind. Thanks!
