### ISSUE TITLE
[lifecycle] provide lifecycle services

### ISSUE THREAD

**Issue by norro** [micro-ROS/rclc#40]
provide lifecycle services for lifecycle nodes, i.e., `change state`, `get current state`, `get available states`.

**Comment by norro** [comment]
Lifecycle services are already created by the state machine's com_interface. Waiting for https://github.com/micro-ROS/rclc/issues/36 to work on their proper integration.

**Comment by norro** [comment]
Blocked by https://github.com/ros2/rclc/issues/35

**Comment by JanStaschulat** [comment]
Close this issue, opened issue at ros2/rclc https://github.com/ros2/rclc/issues/54
