### ISSUE TITLE
CI build job for rclc for Dashing, Eloquent and ros2:master (rolling)

### ISSUE THREAD

**Issue by JanStaschulat** [micro-ROS/rclc#50]
@pablogs9 Could we also have CI job for micro-ROS/rclc to build and test for the releases:
- Dashing
- Eloquent
- Foxy (currently done)
- Rolling (ros2:master)

Then we could fix potential issues before creating PR from micro-ROS/rclc ros2/rclc.

**Comment by pablogs9** [comment]
Hello, @JanStaschulat for sure.

Just using the proper docker image will work? we don't have to change anything in the build process of the RCLC?

I'm going to open a PR with some changes, lets discuss there

**Comment by pablogs9** [comment]
https://github.com/micro-ROS/rclc/pull/51
