### ISSUE TITLE
Repo cleaning

### ISSUE THREAD

**Issue by julionce** [micro-ROS/rclc#7]
The following is a list of suggested actions to clean-up this repo:

- [ ] rebase branch [feature/api_doc] over [crystal] and [dashing],
- [ ] change #5 target branch from [master] to [crystal],
- [ ] open a PR from [feature/api_doc] to [dashing],
- [ ] remove branches: [Crystal], [master] and [develop].

[dashing]: https://github.com/micro-ROS/rclc/tree/dashing
[crystal]: https://github.com/micro-ROS/rclc/tree/crystal
[Crystal]: https://github.com/micro-ROS/rclc/tree/Crystal
[master]: https://github.com/micro-ROS/rclc/tree/master
[develop]: https://github.com/micro-ROS/rclc/tree/develop
[feature/api_doc]: https://github.com/micro-ROS/rclc/tree/feature/api_documentation

**Comment by iluetkeb** [comment]
My last info has been that we will no longer maintain rclc as a project?

**Comment by julionce** [comment]
Sorry, I didn't have news about that. In that case, how should we proceed? Should we close this repo and remove the reference from micro-ros-build?

**Comment by ralph-lange** [comment]
The branch new_api_and_LET_executor_trigger shall replace the original content completely (discussed this in the Real-time Working Group in December 2019). @JanStaschulat will make a PR to ros2/rclc soon. (He is about to finalize the documentation.) I'll clean up the other branches.

**Comment by ralph-lange** [comment]
I just merged (rebased) the API documentation into crystal and dashing. I will remove Crystal and develop as proposed.

**Comment by ralph-lange** [comment]
@JanStaschulat could you please push your changes into master (instead of feature/new_API_LET_executor_trigger), remove the two feature/new_API_LET_executor* branches and later create your PR from micro-ROS/rclc[master] into ros2/rclc[master]?

**Comment by ralph-lange** [comment]
@JanStaschulat works now mainly in the dev branch. The develop branch can be deleted, or @BorjaOuterelo?

**Comment by JanStaschulat** [comment]
@ralph-lange @pablogs9 Can this ticket be closed?

**Comment by pablogs9** [comment]
Yes
