### ISSUE TITLE
Feature request: Logging like ros2 node.get_logger()

### ISSUE THREAD

**Issue by PaddyCube** [micro-ROS/rclc#77]
A ROS2 node provides a handy interface for log messages. Something like node.get_logger().info(). You all know we can view these messages in rqt and other tools.

It seems that such a function is not availabe in micro-ros

BR Patrick

**Comment by JanStaschulat** [comment]
Transferred this ticket to ros2/rclc https://github.com/ros2/rclc/issues/55
