### ISSUE TITLE
spin_some does not fail when agent is disconnected

### ISSUE THREAD

**Issue by bjv-capra** [micro-ROS/rclc#79]
AFAIK, the executor would return a value different to RCL_RET_OK if the agent is disconnected (agent down or link is down).

However, this is not the case. whenever I spin_some, I've tried different ways, by either disconnecting the link(ethernet) or stopping the agent, nonetheless, this gives the same behavior. If I do a ping (using the rmw ping), I get that the agent is down (as expected).

I'm using the foxy branch

**Comment by pablogs9** [comment]
@JanStaschulat is this behavior expected?

**Comment by JanStaschulat** [comment]
@bjv-capra Nice catch. 
When you call `rclc_executor_spin()` the call to `spin_some` is guarded by [testing for a valid ROS context](https://github.com/ros2/rclc/blob/aec6e900cdb12765db71bd4cc990c7de37e2cab2/rclc/src/rclc/executor.c#L1069). This should fail, if the connection to the agent breaks down. Inside the `spin_some()` there is no such test. 

If you want to use `spin_some` directly in your `main` function and want an error message about a missing connections to the agent, you could do it like this: 
```C
if (rcl_context_is_valid(executor->context)) {
  ret = rclc_executor_spin_some(executor, executor->timeout_ns);
  if (!((ret == RCL_RET_OK) || (ret == RCL_RET_TIMEOUT))) {
    PRINT_RCLC_ERROR(main,rclc_executor_spin_some error);
  } 
} else {
    PRINT_RCLC_ERROR(main, no_valid_ROS_context);
}
```
The macro [PRINT_RCLC_ERROR](https://github.com/ros2/rclc/blob/ae58a72168f791df6a328ed4324d8a3b156e1e1b/rclc/include/rclc/types.h#L43) takes two string parameters that are just printed.

**Comment by bjv-capra** [comment]
Thanks @JanStaschulat , that makes sense.

A follow-up question then, will the executor ever give an undefined behavior if I `spin_some` it without a valid context? Doesn't seem like, based on what I've seen on using it and skimming through the code, but maybe I'm mistaken.

**Comment by JanStaschulat** [comment]
@bjv-capra That is a good point. That depends on the implementation of rcl and rmw regarding message handling. The executor creates a wait-set with `rcl_wait_set_init` and also calls `rcl_wait` and `rcl_take`. In `rcl_wait_set_init` [the ROS context is checked, if it is valid](https://github.com/ros2/rcl/blob/80efa3fa0861da45c1f81622763d06fc1f76f129/rcl/src/rcl/wait.c#L129). As [`rcl_wait_set_init` is called in `rclc_executor_spin_some`](https://github.com/ros2/rclc/blob/ae58a72168f791df6a328ed4324d8a3b156e1e1b/rclc/src/rclc/executor.c#L929), the `context` is checked implicitly in each call of `spin_some`.

Additionally, the `context` is a member variable of the `wait_set` (rcl and rmw). - I did not check the entire implementation of `rcl_wait` and `rcl_take`, but I would assume, that the `context` is checked there too.

So, in my opinion, the executor should never give an undefined behavior when calling `spin_some`.

Nevertheless, I'll create a PR, in which I move the test `if (rcl_context_is_valid(executor->context))` from `spin` to `spin_some`. Then, it is waterproof.

**Comment by JanStaschulat** [comment]
@bjv-capra Could you test, if you get an error message when replacing `rclc_executor_spin_some` by `rclc_executor_spin` in the case of connection loss to the Agent?

**Comment by bjv-capra** [comment]
I don't have any prints enabled, so I doubt I'll get any message, but I'll see if I can replace the "blocking" `rclc_executor_spin`

I'll try it out

**Comment by bjv-capra** [comment]
What I have is a node using `rclc_executor_spin` , which seems to work just fine. I have my agent running for a while and then I kill the agent process.

However, the node stills runs on `rclc_executor_spin`, it didn't exit the loop and it'd seem that it still operates as expected (with the exception there is no agent on the other side)

**Comment by JanStaschulat** [comment]
Thanks for this feedback.

**Comment by JanStaschulat** [comment]
Sorry for the delay, I merged a PR https://github.com/ros2/rclc/pull/165 to check the ROS context now in `rclc_executor_spin_some`. 
Does this resolve your problems?

See also Issue: https://github.com/ros2/rclc/issues/109

**Comment by bjv-capra** [comment]
Hi, I haven't been able to test this, I'll see if I can check it out this week as I catch up with work.

However, I did a quick skim through the code and there seems to be a `while(true)` that has no exit on the spin for a period. Maybe I miss understood it.

**Comment by JanStaschulat** [comment]
Hi @bjv-capra , which "`while(true)` that has no exit on the spin for a period" are you refering to?

`rclc_executor_spin`
https://github.com/ros2/rclc/blob/59632f29b6fe93240694d736c474a3584410cd2a/rclc/src/rclc/executor.c#L1348
Inside the while-loop `rclc_executor_spin_some` returns an error, if the ROS context is not available. Then the while-loop is exited with `return`.

`rclc_executor_spin_period`
https://github.com/ros2/rclc/blob/59632f29b6fe93240694d736c474a3584410cd2a/rclc/src/rclc/executor.c#L1398
Inside the while-loop `rclc_executor_spin_some` returns an error, if the ROS context is not available. Then the while-loop is exited with `return`.

`rclc_executor_spin_some`
returns `RCL_RET_ERROR` if ROS context is not available:
https://github.com/ros2/rclc/blob/59632f29b6fe93240694d736c474a3584410cd2a/rclc/src/rclc/executor.c#L1206

**Comment by bjv-capra** [comment]
Never mind, I completely misread the code while quickly skimming through it.

I'll see to test it out this week and be back with some feedback.

**Comment by norro** [comment]
Can this issue be closed?
